### PR TITLE
Reject instead of throwing

### PR DESCRIPTION
**Pull request by likerRr**
Makes interface truly asynchronous like it's done e.g. [here](https://github.com/sindresorhus/opn/blob/master/index.js#L7)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks. It being a breaking change is a stretch, but I'll do a major release just to be sure ;)

**Comment by likerRr** [comment]
Thank you for responsiveness! 

Can you also update the [dependency](https://github.com/yeoman/generator/blob/master/package.json#L45) for yo generator? I initially faced the issue with throwing there.

**Comment by sindresorhus** [comment]
Done, but it's not really up to me when to do another release of `generator`. Ask @SBoudrias.

**Comment by SBoudrias** [comment]
@likerRr PR welcomed on yeoman-generator

**Comment by likerRr** [comment]
@SBoudrias, @sindresorhus has already made a commit to `yeoman-generator`, we just wait for the next minor release :smile:

**Comment by SBoudrias** [comment]
We'll need to bump major as we es6-ify some of the code and removed some callback apis.

**Comment by likerRr** [comment]
@SBoudrias when do you plan to do it?

**Pull request merged**
